hambomb:
  lock:
    agentStrategy: redis
    lock-timeout: 500
    lock-wait-timeout: 500

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100

server:
  port: 8888